### ISSUE TITLE
ETS Gebäudestruktur Export

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#11]
Export der Gebäudestruktur als XML Import für die ETS

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald 
Bitte in der ETS testen und XML export beispiel schicken danke !

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald das ist aktuell nicht relevant. Vielleicht könnte das für einen späteren Zeitpunkt interessant werden. Setz das Thema erstmal auf „Close“. erstmal :)
