### ISSUE TITLE
Default Werte für Objekte und Funktionen

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#12]
Beim Erstellen eines Raumobjektes ist derzeit der default Wert leer. 
Wäre cool, wenn hier einfach die erste Option default ausgewählt wäre. 

![image](https://github.com/LeonardSchwenk/gruppenadressen-generator/assets/23461821/1273a8cb-7923-4d16-964a-1138f2c39644)

**Comment by LeonardSchwenk** [comment]
added with watcher works in dev 
![GIF Recording 2023-11-23 at 7 45 46 AM](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/713cb17f-54bb-4fd9-85bb-f0ba716a761f)


https://github.com/LeonardSchwenk/gruppenadressen-generator/commit/64c92e58a20b094f72f2ca26c11860472bb2d54f
