### ISSUE TITLE
Export nicht vollständig

### ISSUE THREAD

**Issue by skeal** [LeonardSchwenk/public-gruppenadressen-generator#16]
Ich habe testweise einen Raum WC im Stockwerk EG und dort ein Deckenlicht angelegt. Es handelt sich dabei nicht um ein individuelles Objekt sondern um das Standard Deckenlicht.

In der gleichen Sitzung habe ich im Büro im 2. OG mehrere individuelle Objekte zur Beleuchtung angelegt, die funktionieren.

Wie kann ich hier helfen?

Projekt: Dahoam2

**Comment by LeonardSchwenk** [comment]
von KNXBUS:
GA Export nicht möglich: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by sebastiantheobald** [comment]
@skeal danke für dein Feedback! Dein Problem sollte nun behoben sein :)! Meld dich gerne jederzeit, wenn du weitere Probleme hast.
