### ISSUE TITLE
GA Export nicht möglich

### ISSUE THREAD

**Issue by KNXBUS** [LeonardSchwenk/public-gruppenadressen-generator#17]
Folgende Fehlermeldung bekomme ich beim GA-Export
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by sebastiantheobald** [comment]
Hi @KNXBUS, 
ich habe mir das gerade angeschaut: Dein Raum "Boden" hatte kein Stockwerk gepflegt. Ich war so frei "EG" zu setzen. Der Fehler sollte jetzt nicht mehr auftauchen. 

Mit dem nächsten Update (hoffentlich noch heute) werden wir eine Fehlervalidierung einbauen, damit man künftig keinen Raum mehr ohne Stockwerk bzw. ohne Raumname anlegen kann. 

Danke für die Rückmeldung! :)

**Comment by KNXBUS** [comment]
Hallo,

alles OK, danke schön

 

Von: Sebastian Theobald ***@***.***> 
Gesendet: Dienstag, 24. Oktober 2023 08:39
An: LeonardSchwenk/public-gruppenadressen-generator ***@***.***>
Cc: KNXBUS ***@***.***>; Mention ***@***.***>
Betreff: Re: [LeonardSchwenk/public-gruppenadressen-generator] GA Export nicht möglich (Issue #17)

 

Hi @KNXBUS <https://github.com/KNXBUS> ,
ich habe mir das gerade angeschaut: Dein Raum "Boden" hatte kein Stockwerk gepflegt. Ich war so frei "EG" zu setzen. Der Fehler sollte jetzt nicht mehr auftauchen.

Mit dem nächsten Update (hoffentlich noch heute) werden wir eine Fehlervalidierung einbauen, damit man künftig keinen Raum mehr ohne Stockwerk bzw. ohne Raumname anlegen kann.

Danke für die Rückmeldung! :)
