### ISSUE TITLE
Individuelle Benennung / Erstellung von Fluren / Geschossen

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#18]

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald 


Was findest du besser für die UI um das Geschoss selbst benennen zukönnen ?

Find 2. besser (natürlich noch nicht hübsch) -> Wäre dann wie bei dem Individuellen Objektkennungen -> toogle
1.Option
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/29fa13e3-46f2-4f27-8fb8-14fdf29e73bd)


![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/164b586e-0480-4029-b397-8597e9e0f08c)

2. Option
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/44f2486e-9841-4e4b-824b-d65f232042cc)

**Comment by sebastiantheobald** [comment]
Ich würde das global im Projekt festlegen und nicht je Raum. 
Heißt initial die Geschosse festlegen, die man dann vorausgewählt im Raum auswählt.

**Comment by LeonardSchwenk** [comment]
Wie soll das aussehen? Finds besser das man individuell je Raum machen könnte :D ? Wusste nicht, was dagegen sprechen sollte.

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald 
Wie wärs in der Projekt bearbeitung mit einem extra punkt Geschosse ?

Und dann einem Modal in dem man die geschosse editieren kann oder Hinzufügen ?

![Screenshot 2023-12-03 at 12 41 45](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/bde15977-76d2-47a8-ad4c-9c83a69f58af)
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/01d956b8-da54-4992-81db-a1a5af5dd9d8)

**Comment by TheFelix93** [comment]
Also ich wäre dafür, dass man zentral, aber auch direkt bei der Raumerstellung machen können sollte.
Wenn ich ein neues Projektanlege, dann hat man ja noch keine Geschosse angelegt, dann wäre es sehr praktisch, wenn nicht erst wieder rausklicken müsste.

Das ganze sollte dann eine Auswahlbox mit allen bereits angelegten Einträgen sein  + ein Feld zu Anlegen neuer Einträgen.

Umbennenen und löschen, aber nur über das zentrale Menü.

**Comment by sebastiantheobald** [comment]
@TheFelix93 wir haben es uns so überlegt: 

![GIF Recording 2023-12-19 at 12 45 15 PM](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/23461821/837637dc-2c5f-4961-b481-b84af03e2433)

Auf Projekt Ebene definiert man seine Geschosse welche man dann beim Erstellen / Bearbeiten der Räume nutzen kann. ggf. ergänze ich noch, dass man das im Raum machen kann, gute Idee!

**Comment by sebastiantheobald** [comment]
Update: Zunächst können die Geschosse nur über die Projekteinstellungen definiert werden. Im Slideover NewRoom erscheint ein Hinweis, wenn noch kein Geschoss erstellt wurde. 

<img width="680" alt="image" src="https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/23461821/b1f131a8-0b2e-4551-8afe-b5a431268f8a">
