### ISSUE TITLE
Toggle/ Boolean, Geschosse in Gruppenadressen Namen einschließen / auslassen

### ISSUE THREAD

**Issue by LeonardSchwenk** [LeonardSchwenk/public-gruppenadressen-generator#21]
> Fände es super, wenn man mittels Checkbox oder ähnlichen entscheiden kann, ob die Geschosse in den Gruppenadressen-Namen integriert werden sollen.

EG_Flur_Treppenlicht_schalten >> Flur_Treppenlicht_schalten

**Comment by LeonardSchwenk** [comment]
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/67e79841-ffb1-4118-aec8-5bb2d9980202)

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald 
Passt das so? Boolean wert mit und ohne Geschossnamen im export.

**Comment by sebastiantheobald** [comment]
Würde da noch ein Label hinmachen statt alles in die Überschrift. Aber ansonsten joa. 👍

**Comment by sebastiantheobald** [comment]
Fix Layout
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/23461821/d00343c5-66d5-4d31-8a5e-1ce5215f82a4)

**Comment by sebastiantheobald** [comment]
closed
