### ISSUE TITLE
Summe Anzahl der Raumobjekte ausgeben zur besseren Übersicht

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#22]

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald 

Einfach nur die Zahl oder noch mit text oder anderem design elementen ?
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/4997763b-61e0-4feb-a69a-507144f11b6e)

![GIF Recording 2023-12-09 at 9 33 06 AM](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/39e449e6-5a54-4e02-959b-e567d55d9435)

**Comment by sebastiantheobald** [comment]
Würde das in einem Subtitel packen in hell grau und kleinerer Schrift. Direkt drunter oder rechtsbündig neben "Objekte"
