### ISSUE TITLE
Sortierung der Raumobjekte manuell ändern

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#23]
Manuell per Drag and Drop ermöglichen

**Comment by LeonardSchwenk** [comment]
Ist in dev schon möglich.
Kommt mit dem nächsten release.
@sebastiantheobald 
![GIF Recording 2023-12-07 at 8 02 41 AM](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/0ad4d44a-7be7-4a15-b620-62cc291eb0e4)
