### ISSUE TITLE
Umweltsensoren werden zwar in Gruppenadressen struktur angelegt, gibt es aber nicht als entsprechende Objekte in den Räumen

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#25]

**Comment by BenjaminK87** [comment]
Sämtliche Gewerke und Funktionen außer Beleuchtung, Verbraucher, Beschattung, Heizung werden nicht verarbeitet.
Es erscheinen die Hauptgruppe, Mittelgruppe aber keine GA


![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/1beb0961-1f45-40b6-bfa1-1d99d79fc7a5)


![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/b9273d3d-65a5-47db-af3b-658bf9335f8f)
