### ISSUE TITLE
Schalter individuelles Objekt links positionieren

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#27]
Da häufig benutzt links platzieren

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald 
So ? 
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/06922c03-ef6c-43d3-a7ed-5c0c1e18bad9)

**Comment by LeonardSchwenk** [comment]
> I already tried it out and it works fine. From the UX point of view I would
suggest to have the toggle switch before the name input, that makes using
the UI from left to right more intuitive imo
Cheers, Daniel
👍🏻

**Comment by sebastiantheobald** [comment]
@LeonardSchwenk ne, zwischen rein. Vor das Objekt das man benennen will.

**Comment by LeonardSchwenk** [comment]
<img width="640" alt="image" src="https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/03c7a73f-d2dd-43d1-8e6b-2b32253de7fa">
