### ISSUE TITLE
Objekt Vorauwahls

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#28]
> Ich fände es gut, wenn beim Anklicken von "Neues Objekt" gleich die Auswahl
vom vorherigen Objekt übernimmt, als die Kategorie Verbraucher und nicht
immer Beleuchtung, die Auswahl von individuell und auch gleich den letzten
Text aus der Beschreibung. Dann löscht man das letzte Wort / oder Buchstaben
und ergänzt es einfach.

**Comment by LeonardSchwenk** [comment]
Vorauswahlt bei objekten überträgt sich jetzt bei indiviuellem text wie auch beim dropdown:
![GIF Recording 2023-11-27 at 7 01 36 AM](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/66ec1053-f8c8-4f8c-a8b3-b04815945cd6)

**Comment by sebastiantheobald** [comment]
nice!
