### ISSUE TITLE
Neue Elemente  - immer automatisch Beleuchtung

### ISSUE THREAD

**Issue by ChristianSchleif** [LeonardSchwenk/public-gruppenadressen-generator#30]
Wenn man neue Objekte einem Raum hinzufügt, dann wird standardmäßig Beleuchtung verwendet.
Bedeutet:
Ich füge Verbraucher -> Steckdose hinzu
Jetzt möchte ich einen zweiten Verbraucher hinzufügen, er "schlägt" mir dann Beleuchtung vor.
Besser wäre mE, wenn er den letzten Typ übernimmt (also Verbraucher)

Hoffe das ist verständlich geschrieben

**Comment by LeonardSchwenk** [comment]
Hi @ChristianSchleif,
vollkommen richtig 👍🏻, dieses feature haben sich auch schon mehrere user gewünscht.

Dieses Feature ist auch schon eingebaut und kommt auch mit dem nächsten Release :). 

Hier ist das ursprüngliche issue, -> hier gibts auch eine kleine preview durch ein gif.
https://github.com/LeonardSchwenk/public-gruppenadressen-generator/issues/28

Danke für dein feedback und dass du sogar ein Issue aufgemacht hast, das freut uns besonders :)! 

Grüße und frohe Weihnachten 🎄
