### ISSUE TITLE
Mehrere Räume auf einmal erstellen

### ISSUE THREAD

**Issue by ChristianSchleif** [LeonardSchwenk/public-gruppenadressen-generator#31]
Es wäre sicherlich hilfreich, wenn man beim Erstellen der Räume ggf. gleich das ganze Stockwerk erstellen kann. Sprich ich wähle das Stockwert und gebe alle Räume an.

**Comment by LeonardSchwenk** [comment]
@ChristianSchleif 
Finde ich eine top Idee.

Vielleicht ein Checkbox  mit "mehrere räume erstellen".

Dass dann unter Name des Raums ein + Symbol erscheint, das die Möglichkeit bietet, mehrerer neuen Freitexte Felder mit Name des Raumes hinzufügt? 
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/d37a963d-7468-4507-a461-8d565bcae42e)

Werd die tage mal ein Mockup machen, das man sich besser vorstellen kann :)

**Comment by sebastiantheobald** [comment]
UI: 
- Mehrfachauswahl aus Chips (Vorschlägen) in die Geschosse rein.

**Comment by sebastiantheobald** [comment]
Wird in der nächsten Version verfügbar sein :) @ChristianSchleif
