### ISSUE TITLE
Eigene Räume blenden Standart-Räume aus

### ISSUE THREAD

**Issue by ChrisKoh83** [LeonardSchwenk/public-gruppenadressen-generator#35]
Wenn in den Projekeinstellungen ein eigener Raum angelegt wird:

<img width="418" alt="image" src="https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/13451391/b7975671-d6c3-4ede-bce7-17346317ab25">

Kann man nur noch diesen als neuen Raum anlegen:
<img width="664" alt="image" src="https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/13451391/12f6a071-06dd-47a4-af3f-cc6c011f29ef">

**Comment by LeonardSchwenk** [comment]
Hi @ChrisKoh83 und danke für deine zahlreichen Beiträge! 

**Genau, das ist auch so beabsichtigt. 
Du kannst jetzt beliebig viele Geschosse selbst hinzufügen, diese erscheinen dann auch in der Auswahl "Geschoss".**


![Screenshot 2024-01-03 at 16 24 31](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/a09f8b1b-79ed-4f31-84d9-ef85d2de9580)

![Screenshot 2024-01-03 at 16 24 37](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/b411c2f7-82ea-47f5-b2b6-31dd43501f09)


**Die "Standard" Geschosse werden mit dem Erstellen eigener individuellen Geschosse überschrieben.

Die initiale Auswahl an Geschossen besteht nur, wenn du noch keine individuellen Geschosse erstellt hast.**

![Screenshot 2024-01-03 at 16 25 11](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/91a94067-8779-4429-81f7-6afe383b9a16)

![Screenshot 2024-01-03 at 16 25 16](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/19411803-ffed-4470-927b-7e983e153d39)

Ich hoffe, das Passt als Antwort für dich, dann würde ich hiermit das Issue schließen :)

**Comment by ChrisKoh83** [comment]
Danke für die Erklärung! :)
