### ISSUE TITLE
"Neues Objekt" überschreibt bereits getätigte Einstellungen

### ISSUE THREAD

**Issue by jsr4id** [LeonardSchwenk/public-gruppenadressen-generator#37]
Man erstellt ein neues Objekt im Raum und ändert z.B. von Deckenlicht zu Wandlicht:
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/57200946-88b9-4dce-8afd-58eac6c62e84)

Fügt man nun ein neues Objekt hinzu, wird die Einstellung vom ersten Objekt überschrieben und es wechselt, wie hier zu sehen wieder auf Deckenlicht.
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/b0a1af1a-f535-4a06-ac83-4c478482d8cc)

Dieser Fehler tritt nur auf, wenn man die Konfiguration noch nicht gespeichert hat.

**Comment by jsr4id** [comment]
Ebenfalls werden die Einstellungen überschrieben, wenn man die Liste manuell über das "Menuicon" ![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/02106cc3-818d-420d-ba9e-3a35ed1ecf82) sortiert.

**Comment by sebastiantheobald** [comment]
@jsr4id danke für den Bug! Setze ich mich dran :)!

**Comment by sebastiantheobald** [comment]
@jsr4id Problem ist gefunden! Updaten wir in Kürze in die Live-Version.

@LeonardSchwenk habs gerade committet. Kannst du das bitte in die Live Version pushen?

**Comment by LeonardSchwenk** [comment]
live :) @jsr4id 
Könntest du einmal bestätigen das es behoben ist.

Vielen dank nochmal !

**Comment by LeonardSchwenk** [comment]
Korrigieren Issue  ist noch offen @sebastiantheobald

**Comment by jsr4id** [comment]
Kann ich bestätigen. Problem besteht weiterhin.

**Comment by sebastiantheobald** [comment]
wird in V1 behoben
