### ISSUE TITLE
"Raum löschen"-Abfrage bleibt bestehen

### ISSUE THREAD

**Issue by jsr4id** [LeonardSchwenk/public-gruppenadressen-generator#38]
Klickt man auf den Button "Raum löschen" erscheint die Abfrage ob man diesen wirklich löschen möchte:
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/24575ae7-b335-4382-83d4-feb9d79824d4)
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/2b8feccf-564a-4b54-9395-a01f471c2ed2)

Bestätigt man diesen mit "Ja, wirklich löschen" wird dieser aus der Raumliste gelöscht.

Klickt man nun einen anderen Raum an, ist die Abfrage "Raum löschen" immer noch aktiv:
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/5d56552d-c517-4971-9ca1-ff570850bfeb)

**Comment by sebastiantheobald** [comment]
@jsr4id auch diesen Fehler habe ich eben behoben :)! Vielen, vielen Dank fürs melden! 
Wir werden das wie gesagt die Tage live nehmen.

**Comment by LeonardSchwenk** [comment]
live :) @jsr4id  
Könntest du einmal bestätigen das es behoben ist.

Vielen dank nochmal !

**Comment by LeonardSchwenk** [comment]
Korrigieren Issue  ist noch offen @sebastiantheobald

**Comment by jsr4id** [comment]
Kann ich bestätigen. Problem besteht weiterhin.

**Comment by sebastiantheobald** [comment]
Wird in V1 final behoben.

**Comment by sebastiantheobald** [comment]
behoben in V1
