### ISSUE TITLE
Es werden nur GA für Beleuchtung generiert

### ISSUE THREAD

**Issue by dade2080** [LeonardSchwenk/public-gruppenadressen-generator#39]
Es werden nur GA für Beleuchtung generiert. Die anderen Objekte werden nicht berücksichtigt.

**Comment by LeonardSchwenk** [comment]
Hi @dade2080,
Danke für dein Report.
Könntest du uns deine Projekt id mitteilen ?

Wenn du auf dein Projekt klickst kannst du einfach die URL kopieren und die hier Kommentieren.
Danke dir ! 

Grüße,
Leo

**Comment by dade2080** [comment]
Na klar. Link anbei.

https://app.gruppenadressen-generator.de/projects/5yn8As9FQ0CTAfQq1FMp

**Comment by LeonardSchwenk** [comment]
@dade2080 

Müsstest einmal das object löschen und wieder angelegen get der Export dann wieder ?

Danke nochmal :)

**Comment by dade2080** [comment]
Schaut gut aus! Nach der Neuanlage des Raumes inkl. der Objekte, wird alles exportiert!
