### ISSUE TITLE
Beschattung, Heizung und Kontakte GAs werden nicht generiert

### ISSUE THREAD

**Issue by FloSchriewi** [LeonardSchwenk/public-gruppenadressen-generator#40]

**Comment by LeonardSchwenk** [comment]
Hi @FloSchriewi,
Leider hatten wir durch ein update ein fehler eingebaut. 
Du müsstest nur die fehlenden Objekte einmal löschen und wieder anlegen. Dann sollte alles im export erscheinen.
Grüße,
Leo

**Comment by LeonardSchwenk** [comment]
Hi @FloSchriewi ,
gibts hier noch ein update ?
Sonst würde ich das issue schließen :)
