### ISSUE TITLE
Sortierung Geschosse

### ISSUE THREAD

**Issue by hameno** [LeonardSchwenk/public-gruppenadressen-generator#44]
Sowohl in der UI als auch im Export wird die Sortierung der Geschosse aktuell nicht übernommen, d.h. DG kommt vor OG oder EG

**Comment by LeonardSchwenk** [comment]
Hi @hameno,
danke für dein bug Report :) ! 

Wir befinden uns aktuell in der Entwicklung einer neuen (komplett überarbeiteten) Version.

Ich werde dieses Problem als Bug der Version 0 kennzeichnen.

Die neue Version sollte bald verfügbar sein, und mit ihr wird hoffentlich auch dieser Bug behoben sein. 👍🏻 (Wir drücken die Daumen! :D)

Bis dahin bleibt das Issue selbstverständlich offen.

Wir bitten dich noch um ein wenig Geduld bis die neue version da ist!

Sobald die neue Version veröffentlicht ist, wird es definitiv einen Beitrag im Newsletter geben!

Cheers,
Leo

**Comment by sebastiantheobald** [comment]
@LeonardSchwenk push - bitte bei Generierung GAs berücksichtigen

**Comment by sebastiantheobald** [comment]
Immer noch aktuell in V1

**Comment by LeonardSchwenk** [comment]
Fixed :)
