### ISSUE TITLE
"Raum löschen"-Abfrage bleibt bestehen bei Menü schließen

### ISSUE THREAD

**Issue by jsr4id** [LeonardSchwenk/public-gruppenadressen-generator#46]
In Bezug zu folgendem Issue:
[https://github.com/LeonardSchwenk/public-gruppenadressen-generator/issues/38](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/issues/38
)
tritt der Fehler in einem anderen Fall immer noch auf.

Klickt man auf "Raum löschen" und schließt das Canvas-Menü über den "Schließen-Button" rechts oben oder indem man in den Hauptbereich klickt, bleibt die Abfrage weiterhin bestehen. Auch dann, wenn man einen anderen Raum aufruft.

**Comment by LeonardSchwenk** [comment]
@jsr4id Vielen dank für dein 1a Feeback 👍🏻 ! Traum und sehr aufmerksam und detailliert! 


## Problem
https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/09a7f9f3-30bf-473d-b2d5-5bf4b2f645d5


## Fix
https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/d70b001d-bf1f-4d64-87d8-a870f0d788fe
