### ISSUE TITLE
Falsche Benennung "Anzahl Geschosse"

### ISSUE THREAD

**Issue by jsr4id** [LeonardSchwenk/public-gruppenadressen-generator#47]
In der Hauptansicht eines Projektes sollte unter **Räume** die Bezeichnung "Anzahl Räume" in "Anzahl Geschosse" geändert werden.
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/e62af696-6a5c-4ac6-8b76-f98a901c2b9e)

**Comment by LeonardSchwenk** [comment]
Ist gefixt! :) Habe es bei **Anzahl Räume** gelassen, scheint übersichtlicher, da es definitiv mehr Räume als Geschosse geben wird.

https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/d3768c0e-9c90-4cd0-92c2-3054ff70159b
