### ISSUE TITLE
Umbenennung der Geschosse nicht möglich

### ISSUE THREAD

**Issue by jsr4id** [LeonardSchwenk/public-gruppenadressen-generator#48]
Benennt man ein Geschoss in den Projekteinstellungen um - z.B.: von "**1. OG**" in "**OG**" :
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/076352a0-e546-4c03-b10d-6d433341b4dc)
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/db2705cf-a080-43da-8ef3-f992a6033dc9)
und speichert die Änderung, steht im Projekt immer noch "**1. OG**".
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/1e782d50-cbfc-4a94-8293-364055123bb8)

**Comment by LeonardSchwenk** [comment]
Fixed ! 
Sortierung funktioniert auch aber aktuell nur in der UI, wird hier weitergeführt.
https://github.com/LeonardSchwenk/public-gruppenadressen-generator/issues/44
