### ISSUE TITLE
Vorschau-Funktion auch in der Basis-Version aufrufbar

### ISSUE THREAD

**Issue by jsr4id** [LeonardSchwenk/public-gruppenadressen-generator#49]
Das Pro-Feature ist auch in der Basis Version aufrufbar.
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/19953956/4ac640ee-2582-4edd-be08-4b8d89825012)

**Comment by LeonardSchwenk** [comment]
Hi @jsr4id,
wir werden die Vorschau erstmal auch für die Basis Version behalten :) ! 
Danke dir!
