### ISSUE TITLE
Import in ETS6 nicht möglich

### ISSUE THREAD

**Issue by BenjaminK87** [LeonardSchwenk/public-gruppenadressen-generator#50]
Beim Export sind die Gruppen alle verschoben, werden teilweise nicht importiert
![Unbenannt](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/29157462-64af-463b-8b72-2d304e31ab8d)

![Unbenannt1](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/a04dfed6-963d-4019-977e-5c67e80a8eca)

1/1 Dimmen ist leer
in 1/2 sind die GAs von 1/1

![Unbenannt3](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/e2796a11-677a-41ee-bddd-cea19296d3d9)

**Comment by LeonardSchwenk** [comment]
Hi @BenjaminK87,
das ist natürlich gar nichts.
Würdest du mir einmal deine Projekt id schicken?
Diese findest du in der URL, wenn du auf das Projekt geklickt hast.
Danke dir vielmals
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/fda434a9-5614-458b-84fa-1e27e41ceb35)

**Comment by LeonardSchwenk** [comment]
scheint verruscht zusein !

![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/6aa9ea7f-54f2-4efa-a0be-67b53d2b3e13)

**Comment by LeonardSchwenk** [comment]
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/9be59931-2d5e-4fa1-951a-cb656aa03294)

**Comment by BenjaminK87** [comment]
Na klar gerne.
ZMGeFVP9p0FCys3Ytww6

**Comment by LeonardSchwenk** [comment]
Ist gefixed :) gerne nochmal bestätigen sorry für den Umstand und Danke fürs aufmerksam machen!

**Comment by BenjaminK87** [comment]
Export funktioniert. Top.

Die Feuchte Sensor, Präsenzmelder werden leider noch nicht exportiert. Erscheinen auch nicht in der Vorschau.

**Comment by LeonardSchwenk** [comment]
Würde das in diesem https://github.com/LeonardSchwenk/public-gruppenadressen-generator/issues/25 issue fortführen
