### ISSUE TITLE
Ein oder mehrere Objekte haben keinen Namen oder gehören nicht zum definieren Objekt Gewerk

### ISSUE THREAD

**Issue by BenjaminK87** [LeonardSchwenk/public-gruppenadressen-generator#51]
Ist irgendwie passiert nachdem ich Objekte hinzugefügt/gelöscht habe.

![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/ab7e7c97-be35-425c-8e45-a43e7e579850)

**Comment by BenjaminK87** [comment]
Durch weiteres Hinzufügen, löschen, umbenennen, speichern konnte es irgendwie überzeugt werden weg zu gehen.

**Comment by LeonardSchwenk** [comment]
Hi @BenjaminK87,
es ist schwer zu reproduzieren. Es könnte alles Mögliche sein, vom Browser hängt bis hin zu schlechtem Internet. Der Fehler sagt auch bereits, was falsch ist: dass ein Objekt, das angeblich leer ist, natürlich sieht man, dass eigentlich keines leer ist :D. Das Neuladen des Browserfensters kann auch eine Lösung sein, oder über deinen Weg, dass du das fehlerhafte Objekt gelöscht und erneut hinzugefügt hast.
