### ISSUE TITLE
Sortierung Funktionen wird nicht übernommen

### ISSUE THREAD

**Issue by BenjaminK87** [LeonardSchwenk/public-gruppenadressen-generator#52]
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/0f87261e-d7c0-4a60-8601-dc1f42c936e4)

![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/33461354/4de5b0ce-1680-40f6-a153-15e692180ff9)

Wie man die GA sortieren möchte, wäre auch noch super als Einstellung.

**Comment by LeonardSchwenk** [comment]
Hi @BenjaminK87,

da es den Export betrifft, betrifft es aktuell auch die Vorschau.
Wird hier weiter geführt.
https://github.com/LeonardSchwenk/public-gruppenadressen-generator/issues/44

**Comment by LeonardSchwenk** [comment]
Fixed :)

**Comment by BenjaminK87** [comment]
👍
