### ISSUE TITLE
Bug: 500 error in preview/export

### ISSUE THREAD

**Issue by DanDits** [LeonardSchwenk/public-gruppenadressen-generator#53]
Hi there. I get a 500 error, response contains "isPlanActive", so I assume something goes wrong with the license validation. I have a "Heimwerkerlizenz" that I assume you auto-upgraded from the test trial (thanks for that :) ). I created a new project and upgraded that to expert-mode. I think I could get a preview before I created rooms and objects, maybe that was also before upgrading this project.
Can you please have a look, I really need that today if possible or else no switch in my house will do anything.

**Comment by LeonardSchwenk** [comment]
@DanDits 
Sorry for the inconvenience.
Im on a trip today, I tried to implement a quick fix.
Can you tell me if it worked and you projected ? 
I will look into it in the evening today.

**Comment by DanDits** [comment]
Thanks for the quick reply, awesome, the workaround did the trick. 
Side note: I will collect feedback during this personal project. But I also have contact to a company working in this area (electrical planning), they might also be interested, so far it looks very promising what you guys improved in the last months

**Comment by LeonardSchwenk** [comment]
Glad it worked!
Great, we would love your feedback! 
Thank you already! Very nice of you, we appreciate that you see our hard work.
We also had a user forum and collected great feedback.
We are missing an example project for sure and tutorials :). Also, reshaping licensing for more clarity.

**Comment by LeonardSchwenk** [comment]
Also, properly fixed the license check now :) !
If you have any problems let us know we will try to solve it asap.
