### ISSUE TITLE
Fehler beim Abrufen der Daten. Bitte kontaktiere einen Admin

### ISSUE THREAD

**Issue by stevecrown** [LeonardSchwenk/public-gruppenadressen-generator#54]
Hi, Ich bekomme folgenden Fehler wenn ich auf die Vorschau klicke:
![msedge_z5ja6nXOHU](https://github.com/user-attachments/assets/3a0a4d66-f451-43c3-9eb0-a44ef49343d3)

Exportieren geht auch nicht mehr!

Habe meine letzten Änderungen Rückgängig gemacht aber kein Erfolg.
Auch wird nicht auf einen konkreten Fehler hingewiesen.

**Comment by LeonardSchwenk** [comment]
Hi @stevecrown,
könntest du mir deine Projekt id mitteilen ?
Die findest du in der URL deines Projektes oder du clickst auf dein Projekt und schickst die URL.
<img width="505" alt="Screenshot 2024-07-18 at 15 43 45" src="https://github.com/user-attachments/assets/8549fbee-4e13-4f2c-bad9-630b583451f5">

Danke dir !

**Comment by LeonardSchwenk** [comment]
Gefunden :) gucks mir nacher an !
VEYoNio3lzMeN0L279E5

**Comment by stevecrown** [comment]
Perfekt, danke :)

**Comment by LeonardSchwenk** [comment]
Hi, @stevecrown,
Stark! 😊

Ich vermute, dass du etwas gelöscht hast, das jedoch noch an einer anderen Stelle referenziert wurde. Normalerweise würde in diesem Fall eine Fehlermeldung erscheinen und der Raum wäre rot umrandet.

Vielen Dank für deine Unterstützung und deine schnelle Rückmeldung!

Gibt auch bald wieder ein Update, dann gibt es auch ein Beispiel Projekt und mehr funktionen :).
Grüße,
Leo

**Comment by stevecrown** [comment]
Danke, @LeonardSchwenk, bin schon gespannt :) 
Mag den Generator.

Grüße
Stefan
