### ISSUE TITLE
Aufbau der GA

### ISSUE THREAD

**Issue by stevecrown** [LeonardSchwenk/public-gruppenadressen-generator#55]
Hi, habe eine Verständnisfrage.
Warum sind Gewerke und Funktionen in den Einstellungen nach:
Gewerke > Funktionen > Objekt 
und nicht nach 
Gewerke > Objekt > Funktionen 
aufgebaut 

Ich habe mir den Export angesehen und es generiert viele unnütze GA.
Z.B. beim Reed
- Status
- Temperatur
- Helligkeit

Ich brauche bei meinem Projekt noch weitere Funktionen und da wäre es doch besser 

-Kontakte
--Reed
---Status
--Temperatursensor
---Temperatur
--Präsenzmelder
---Status
---Helligkeit
---Temperatur
---frei

Oder?
Wenn ich TW oder RGBW konfiguriere wirds unübersichtlich.

Danke und Gruß

**Comment by sebastiantheobald** [comment]
@stevecrown die Reihenfolge ist die von uns vorgegebene Standard-Reihenfolge. Wenn du eine Pro Lizenz hast kannst du das ganz flexibel anpassen. In Kürze launchen wir die Heimwerker Lizenz und in Zuge dessen auch weitere umfassende Anpassungsmöglichkeiten. Du wirst dir damit alles bauen können, was du benötigst. 

Beantwortet das deine Frage?

**Comment by stevecrown** [comment]
@sebastiantheobald , Ja perfekt Danke.
Dann warte ich auf die neue Version.

**Comment by LeonardSchwenk** [comment]
Update is draußen schonmal vorab :) newsletter kommt auch noch die tage !
