### ISSUE TITLE
Fehler bei Konfiguration des Aufbau des Gruppenadressen-Namens

### ISSUE THREAD

**Issue by bihratz** [LeonardSchwenk/public-gruppenadressen-generator#58]
Hallo,
es gib anscheinend einen Bug bei der Erstellung des Gruppenadressen-Namens: egal an welche stelle man die "Funktion" in den Einstellungen schiebt, wird diese in der Vorschau und im Export immer an letzter Stelle des Gruppennamen gestellt.

**Comment by LeonardSchwenk** [comment]
Hi @bihratz,
Vielen dank für dein bug report, gucke ich mir schnellstmöglich an :) !

**Comment by LeonardSchwenk** [comment]
Hi @bihratz,
ist gefixed :) ! 
Danke nochmal für dein Feedback !
