### ISSUE TITLE
Raumsortierung nach Geschossen

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#6]

**Comment by LeonardSchwenk** [comment]
UG sollte noch vor EG sein 🥲 sonst ist das eingebaut, richtig ?
@sebastiantheobald 
![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/0006b59e-f680-4a5a-9ea8-8450f4e90f7b)

**Comment by sebastiantheobald** [comment]
Richtig ja, ist erzeit einfach gruppiert, ohne alphabetische Sortierung. Will das auch nicht nur so definieren, weil könnte auch ein zweites UG geben, oder Garten, oder sonstiges. Will ich dann mit der custom Benennung von Floors implementieren

**Comment by LeonardSchwenk** [comment]
Sorting implemented Weiterentwicklung mit individueller Raumbenennung hier

#18 

![image](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/cc28ef8a-ae55-4157-89dd-490e8e200506)
