### ISSUE TITLE
Max Mittelgruppen sollen 8 sein nicht 32 (HG)

### ISSUE THREAD

**Issue by simonschaubel** [LeonardSchwenk/public-gruppenadressen-generator#60]
![image](https://github.com/user-attachments/assets/3b588a24-29b3-4547-bb74-221ee0c678f8)

**Comment by simonschaubel** [comment]
Ebenfalls scheint der Fehler weiter "aufzupoppen" obwohl die Anzahl angepasst wurde. Jedenfalls gab es keine Fehler in der ETS

**Comment by simonschaubel** [comment]
Könnt ihr bitte ein Warnung/Hinweis hinzufügen, dass es bereits eine "Zentral" Mittelgruppe gibt? Dies wird erst sichtbar bei export.

**Comment by LeonardSchwenk** [comment]
> Ebenfalls scheint der Fehler weiter "aufzupoppen" obwohl die Anzahl angepasst wurde. Jedenfalls gab es keine Fehler in der ETS

Auch nach einem website refresh ?

**Comment by LeonardSchwenk** [comment]
> Könnt ihr bitte ein Warnung/Hinweis hinzufügen, dass es bereits eine "Zentral" Mittelgruppe gibt? Dies wird erst sichtbar bei export.

Aktuell legen wir immer Zentral an :). Dies kann man aber auch Herausnehmen über folgendes toggle.
![Screenshot 2024-10-13 at 14 27 32](https://github.com/user-attachments/assets/61a93d4b-0b4f-46ce-a81d-467168a72c26)

**Comment by simonschaubel** [comment]
> > Könnt ihr bitte ein Warnung/Hinweis hinzufügen, dass es bereits eine "Zentral" Mittelgruppe gibt? Dies wird erst sichtbar bei export.
> 
> Aktuell legen wir immer Zentral an :). Dies kann man aber auch Herausnehmen über folgendes toggle. ![Screenshot 2024-10-13 at 14 27 32](https://private-user-images.githubusercontent.com/26769569/376034438-61a93d4b-0b4f-46ce-a81d-467168a72c26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjY5MzUsIm5iZiI6MTcyODgyNjYzNSwicGF0aCI6Ii8yNjc2OTU2OS8zNzYwMzQ0MzgtNjFhOTNkNGItMGI0Zi00NmNlLWE4MWQtNDY3MTY4YTcyYzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEzMzcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MTJjYjNhNTVmYzA4NDEwZmRjZmVlOTE4MGE1MDEyNTYwZDc2YTk3NGM4NGEyYTIwMDdjN2IxZDE3NmM5NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.riGAsfts1AdkLsIlCkDxurNY-tBWqkWe8BKotlXMUaU)

Das passt schon - es war mir nur nicht transparent bei der Erstellung der Mittelgruppen, daher könnte ein Hinweis helfen, dass bereits eine weg ist für Zentral.

**Comment by simonschaubel** [comment]
> > Ebenfalls scheint der Fehler weiter "aufzupoppen" obwohl die Anzahl angepasst wurde. Jedenfalls gab es keine Fehler in der ETS
> 
> Auch nach einem website refresh ?

Jep kommt immer noch - obwohl ich es doppelt geprüft habe, dass nicht mehr als 7 Objekte vorhanden sind und die ETS meckert ebenfalls nicht.

**Comment by LeonardSchwenk** [comment]
> > > Ebenfalls scheint der Fehler weiter "aufzupoppen" obwohl die Anzahl angepasst wurde. Jedenfalls gab es keine Fehler in der ETS
> > 
> > 
> > Auch nach einem website refresh ?
> 
> Jep kommt immer noch - obwohl ich es doppelt geprüft habe, dass nicht mehr als 7 Objekte vorhanden sind und die ETS meckert ebenfalls nicht.

Guck ich mir die Woche an :)! 
Danke

**Comment by LeonardSchwenk** [comment]
@simonschaubel 
Habs angepasst.
Gerne nochmal bestätigen :).
Danke und wie immer schönes WE
