### ISSUE TITLE
Räume Position verschieben/anpassen

### ISSUE THREAD

**Issue by simonschaubel** [LeonardSchwenk/public-gruppenadressen-generator#62]
So erstmal etwas Feedback: 
Ich finde den Gruppenadressen Generator einfach Klasse, erfüllt bis jetzt alle meine Wünsche und Bedürfnisse! Klasse.

Ich würde mir noch wünschen, die Position der Räume anpassen zu können, da diese 1zu1 in der xml und ETS übernommen werden.
![image](https://github.com/user-attachments/assets/afbc43ff-c4ce-4078-bcc0-2df4a3b85719)

**Comment by LeonardSchwenk** [comment]
Hi @simonschaubel,
vielen Dank für dein hammer Feedback – das freut uns sehr! :)

Auch danke für deine Verbesserungsvorschläge – immer her damit, wir sind immer offen dafür!

Das Feature, das du dir wünschst, wurde schon einmal angefragt und ist bereits in Arbeit, aber noch nicht ganz fertig. Ich werde dieses Issue hier schließen und es im anderen Issue weiter verfolgen. :)


https://github.com/LeonardSchwenk/public-gruppenadressen-generator/issues/56

**Comment by LeonardSchwenk** [comment]
@simonschaubel drag and drop room is live :) 
Freu mich über feedback, ist auch Geschoss übergreifend

**Comment by simonschaubel** [comment]
Mega - super easy!

**Comment by simonschaubel** [comment]
@LeonardSchwenk kann es sein, dass sich die Geschossreihenfolge verschoben hat. Meine Konfig sieht so aus: 
![image](https://github.com/user-attachments/assets/fe5367ba-7240-4272-8127-35c6bad5f378) in der Übersicht, ist jedoch EG und DG getauscht.
![image](https://github.com/user-attachments/assets/6fc8b16b-1655-4f87-914d-d0971a97457b)

**Comment by LeonardSchwenk** [comment]
@simonschaubel Traum, sehr aufmerksam von dir 😅 sollte gleich online sein habs gefixed. 
Gerne nochmal bestätigen thanks ;)
