### ISSUE TITLE
Angelegte Funktionen/Objekte von Gewerken nicht auswählbar

### ISSUE THREAD

**Issue by jola5** [LeonardSchwenk/public-gruppenadressen-generator#63]
# Detailed description
Ich habe ein Projekt im Demo-Modus angelegt und vor einigen Tagen die Heimwerker-Lizenz für das bestehende Projekt erworben. Damit habe ich nun munter das Projekt meinen Bedürfnissen angepasst und dabei so ziemlich alles (Stockwerke, Räume, Gewerke, Funktionen, Objekte) angelegt, wieder gelöscht und angepasst.

Leider kann ich die in den Gewerken neu erstellten Funktionen und Objekte im Projekt über den Button "Neues Objekt" nicht hinzufügen. ~~Stattdessen gibt es einen Eintrag "OBJEKT", den nich nicht angelegt habe und bei dessen Auswahl das "Objekt" Drop-Down rot markiert wird.~~ [[works as intended]]

Ich würde zur Not - mit der Hoffnung, das dass was hilft - auch mit einem neuen blanken Projekt starten. Da die Heimwerker Lizenz aber Projekt gebunden ist wäre das - ganz absehen von der ganzen Arbeit - keine Option.

## Steps to reproduce
1. Bestehendes Projekt öffnen
2. Projekt Einstellungen auswählen
3. Zum Abschnitt "Gewerke und Funktionen" scrollen
4. Gewerk auswählen "Funktion bearbeiten"
5. Beliebig Sets, Funktionen, Objekte erstellen
6. "Zur Projektübersicht" wechseln
7. Beliebigen Raum auswählen
8. "Neues Objekt" erzeugen

## Expected result
Die zuvor angelegten Gewerk/Objektart/Objekt sind auswählbar.

## Actual result
Angelegte Gewerke sind auswählbar. Objektart/Objekt sind keiner ersichtlichen Logik folgend nicht, oder nur teilweise auswählbar. 
~~Im Drop-Down von "Objekt" gibt es einen neuen Eintrag "OBJEKT" (welchen ich nicht angelegt habe), bei dessen Auswahl wird das Drop-Down rot umrandet.~~ [[works as intended]]

## Severity and priority
Die bezahlten Premium Features kann ich so nicht nutzen.

## Environment and version information
Projekt mit Heimwerker Lizenz
Projekt ID: fnm5mWhMBZ6x1GNyzJ9G
Browser: bei Firefox (131.0.3 (64-bit)) und Edge (130.0.2849.56 (Official build) (64-bit) Microsoft) identisches Verhalten 

## Screenshots, videos, or logs
![image](https://github.com/user-attachments/assets/8ee5a02c-2e35-4daf-bfc4-07d24b152ecb)

https://github.com/user-attachments/assets/53fe4fdc-358b-4cad-ae44-2952b4d865cc

**Comment by sebastiantheobald** [comment]
@jola5 Danke für deine ausführliche Fehlerbeschreibung. Ich habe mir das eben mal angeschaut: 

- Das Verhalten bei der Gewerk Auswahl "System" (rote Umrandung) ist vollkommen richtig. "OBJEKT" ist der leere Platzhalter. Du musst ein Objekt auswählen. In diesem Fall "Bus". Wenn du das tust klappt alles. 
- das andere Problem ist tatsächlich eins - ich bin dran. Konnte ich nicht direkt lösen!

**Comment by LeonardSchwenk** [comment]
@jola5 Ich hab noch nie einen so schönen Bug Report gesehen 🥹. Das hilft dir jetzt akut nicht, aber VIELEN DANK.

**Comment by jola5** [comment]
Danke für die Klarstellung mit dem 'OBJEKT'. Dass das der Normalfall ist, war mir vom ursprünglichen Projekt und Funktionsumfang nicht bewusst. Ich dachte das hängt irgendwie zusammen. Mich hat dann wohl verwirrt, dass es bei Objekt einen solchen leere Platzhalter gibt, bei Objektart allerdings nicht, auch nicht beim Gewerk. 

Ich hab die Bug-Beschreibung angpasst.

**Comment by LeonardSchwenk** [comment]
@jola5.
Das ist jetzt vielleicht nicht ganz zufriedenstellend, aber es sollte wieder funktionieren. Ich konnte das Problem leider nicht reproduzieren. Ich habe lediglich das Gewerk gelöscht und neu hinzugefügt. Kannst du bestätigen, dass es jetzt funktioniert?

Es sieht so aus, als hätte sich eine interne ID beim Zählen "verschluckt" und wurde falsch weitergeführt.
Ich kann es mir aktuell noch nicht genau erklären. Meine Vermutung ist, dass vielleicht etwas hin- und hergelöscht oder umbenannt wurde – aber eigentlich sollte das nicht das Problem sein. Sehr strange..
Werde morgen nochmal mit @sebastiantheobald  darüber sprechen, um der Ursache genauer auf den Grund zu gehen.

**Comment by LeonardSchwenk** [comment]
@jola5 Ich schließe das Ticket. Falls der Fehler weiterhin auftritt, öffne es gerne wieder.

**Comment by jola5** [comment]
Danke für die schnelle Bearbeitung. So funktioniert es wieder bei mir.
