### ISSUE TITLE
Mit aktivierter Option "Zentrale Gruppenadressen in jeder Ebene anlegen" können zu viele Mittelgruppen erzeugt werden

### ISSUE THREAD

**Issue by jola5** [LeonardSchwenk/public-gruppenadressen-generator#65]
# Detailed description
Wird die Option "Zentrale Gruppenadressen in jeder Ebene anlegen" aktiviert und lege ich das Projekt so an, dass ich 8 Mittelgruppen (im 3 stufigen Adress-Stil) definiere, werden durch die zusätzliche Zentral Gruppe insgesamt zu viele / ungültige Mittelgruppen erzeugt.

## Steps to reproduce
1. Projekt öffnen
2. Zu "Projekt Einstellungen" wechseln
3. "Aufbau der Gruppenadressen Struktur" --> "Zentrale Gruppenadressen in jeder Ebene anlegen" aktivieren
4. "Aufbau der Gruppenadressen Struktur" --> "Mittelgruppe" --> "Gewerk" auswählen
5. "Gewerke und Funktionen" --> 8 Gewerke anlegen
6. "Gruppenadressen-Stil" --> "3 Stufen Stil" auswählen
7. "Zur Projektübersicht" wechseln
8. Projekt/Adressen exportieren

## Expected result
Der Export lässt sich in ETS importieren.

## Actual result
Im Export sind mit den zusätzlich angelegten "Zentral" Mittelgruppen in Summe 9 Mittelgruppen erzeugt worden. Das wird nicht erkannt, es gibt keine Fehlermeldung vom Generator. Der Export lässt sich in ETS folgerichtig nicht fehlerfrei importieren.

## Environment and version information
Projekt mit Heimwerker Lizenz
Projekt ID: fnm5mWhMBZ6x1GNyzJ9G
Browser: bei Firefox (131.0.3 (64-bit)) und Edge (130.0.2849.56 (Official build) (64-bit) Microsoft) identisches Verhalten 

## Screenshots, videos, or logs
```XML
	<GroupRange Name="01-ZE Hauptverteilung" RangeStart="2048" RangeEnd="4095">
		<GroupRange Name="Zentral" RangeStart="2048" RangeEnd="2303">
		</GroupRange>
		<GroupRange Name="Beleuchtung" RangeStart="2304" RangeEnd="2559">
		</GroupRange>
		<GroupRange Name="Verbraucher" RangeStart="2560" RangeEnd="2815">
		</GroupRange>
		<GroupRange Name="Beschattung" RangeStart="2816" RangeEnd="3071">
		</GroupRange>
		<GroupRange Name="HVAC" RangeStart="3072" RangeEnd="3327">
		</GroupRange>
		<GroupRange Name="Kontakte/Melder" RangeStart="3328" RangeEnd="3583">
		</GroupRange>
		<GroupRange Name="Umweltbedingungen" RangeStart="3584" RangeEnd="3839">
		</GroupRange>
		<GroupRange Name="Aktoren/Antriebe/Tore" RangeStart="3840" RangeEnd="4095">
		</GroupRange>
		<GroupRange Name="System" RangeStart="4096" RangeEnd="4351"> <!-- ZU VIEL -->
		</GroupRange>
	</GroupRange>
```

![ETS6N_E7esRaPfE9](https://github.com/user-attachments/assets/97bbcbb9-3581-41ba-8028-ff8f27745e40)

**Comment by LeonardSchwenk** [comment]
@jola5  Gefunden, durch die Einstellung ist Zentral ist mir das durchgeflutscht.
Danke, für den Report Exception wurde gefixed !
Gerne nochmal rückmeldung geben obs jetzt passt, dann close ich das issue.

**Comment by jola5** [comment]
Ja, beim Export wird es geprüft und entsprechend ein Fehler geworfen. 

Schade ist, dass es nicht schon früher validiert wird. Beim Speichern der Projekteinstellungen (8 Gewerke plus Zentrale Gruppenadressen) wäre es für den Benutzer einleuchtender. So kann es sein (wie bei mir), dass der Benutzer eine ungültige Kombination an Anzahl Mittelgruppen und die zentralen Gruppenadressen einstellt, dann weiter am Projekt arbeitet und erst Tage später damit konfrontiert wird, dass das gewünschte Adress-Schema so nicht funktioniert.

**Comment by LeonardSchwenk** [comment]
@jola5  Wir haben uns gegen eine aufdringliche Infobox in den Einstellungen entschieden, da die Adressaufteilung durch einen einfachen Klick wieder funktionsfähig gemacht werden kann. Eine Infobox in den Projekteinstellungen wäre dennoch hilfreich. Sie könnte dezent platziert sein und liefert die nötige Information, sobald die Aufteilung geändert wird. In meinen Augen muss diese Infobox nicht einmal dynamisch sein.

<img width="1141" alt="image" src="https://github.com/user-attachments/assets/02a277b5-6b5a-4298-aefb-ce97844fa34a">

**Comment by sebastiantheobald** [comment]
@jola5 wir bauen einen Hinweis auf die Settingspage, der dir live anzeigt, wie viele Mittelgruppen und Hauptgruppen mit dem aktuellen Setting verwendet werden und ob deine Settings somit valide sind oder nicht.
