### ISSUE TITLE
Zusätzliche Vorauswahl für Objekte

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#7]
Zusätzliche Vorauswahl für Objekte in den verschiedenen Gewerken. 

## Sammlung

- [x] Stehlampe (Verbraucher, Beleuchtung)
- [x] Dachfenster (Verbraucher)
- [x] Präsenzmelder (Kontakte)

**Comment by sebastiantheobald** [comment]
Stehlampe, Dachfenster & Präsenzmelder der Auswahl hinzugefügt.

**Comment by LeonardSchwenk** [comment]
@sebastiantheobald kann ich das schließen ?

**Comment by sebastiantheobald** [comment]
yes
