### ISSUE TITLE
Individuelle Auswahl des Gruppenadressen Systems / des Aufbaus

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#8]
> Beispiel Beleuchtung: Bei aktuellen Dimmern habe ich noch Gruppenadressen wie "Lastmessung starten" oder "Diagnose". In welche Mittelgruppen soll ich die stecken? Wo kann ich diese Gruppenadressen anlegen und definieren? Gleiches bei den Jalousien. Wo stecke ich Gruppenadressen hin "Verfahrstatus", oder "Status obere Position", "Status untere Position", "Laufzeitmessung starten" hin? Dieses Mittelgruppensystem gehört aus meiner Sicht schon länger abgeschafft.

>Schön wäre eine Auswahlmöglichkeit, ich nutze gerne Raum/Gewerk/Funktion (Gerade erst wieder ein Projekt mit 22 Wohnungen, also Wohnung/Gewerk/Funktion)

[Quelle](https://knx-user-forum.de/forum/playground/ga-wizzard/1900965-gruppenadressen-generator?p=1901411#post1901411)

**Comment by LeonardSchwenk** [comment]
Wie wärs mit einem "Expertenmodus" ?

Default:
> Raum/Gewerk/Funktion 

Experten Optione Beispiel:
- Wohnung/Gewerk/Funktion

![GIF Recording 2023-11-23 at 8 29 34 AM](https://github.com/LeonardSchwenk/public-gruppenadressen-generator/assets/26769569/cf193094-5eda-4f97-a4eb-a2317aa44d51)


Der expertenmodus könnte auch weitere features beinhalten wie -> Gewerkordnungsanpassung

**Comment by sebastiantheobald** [comment]
coole Idee ja!
