### ISSUE TITLE
Zusätzliche Mittelgruppen je Gewerk

### ISSUE THREAD

**Issue by sebastiantheobald** [LeonardSchwenk/public-gruppenadressen-generator#9]
# Sammlung

## Beschattung 
- [ ] Verfahrstatus
- [ ] Status obere Position
- [ ] Status untere Position
- [ ] Laufzeitmessung starten

## Beschattung 
- [ ] Lastmessung starten
- [ ] Diagnose

**Comment by LeonardSchwenk** [comment]
Maximale Anzahl Mittelgruppen pro Hauptgruppe: 8 [0-7]

@sebastiantheobald 

Erweitern bei expertenmodus
